version: "2"

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - unconvert
    - bodyclose      # Checks HTTP response body is closed
    - copyloopvar    # Detects places where loop variables are copied
    - dupword        # Checks for duplicate words
    - errorlint      # Problems with error wrapping (Go 1.13+)
    - noctx          # Finds sending http request without context.Context
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: false
      enable:
        - atomic
        - bools
        - buildtag
        - nilfunc
        - printf
    misspell:
      locale: US
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - errcheck
          - unparam
        text: "always nil"
      - path: 'cmd/'
        linters:
          - errcheck
      - path: 'main\.go'
        linters:
          - staticcheck
        text: "SA1019.*plugin.Debug"
      - linters:
          - staticcheck
        text: "SA1019.*Read is deprecated"

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
    goimports:
      local-prefixes:
        - github.com/iilei/terraform-provider-idgen

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  go: '1.25'

# changelog:
#   use: git
#   sort: asc

release:
  footer: |
    ## Notes

    This is an automated release.  For a curated changelog, see [CHANGELOG.md](https://github.com/iilei/terraform-provider-idgen/blob/master/CHANGELOG.md).
